name: cd

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env: 
  AWS_REGION: eu-west-2
  ECR_REPOSITORY: testeksdeployment
  SHORT_SHA: $(echo ${{ github.sha }} | cut -c 1-8)
  EKS_CLUSTER_NAME: devopsthehardway-cluster
  K8S_NAMESPACE: default
  K8S_DEPLOYMENT: queue
  
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
    - id: step1
      run: echo "test=hello" >> $GITHUB_OUTPUT
    - id: step2
      run: echo "test=world" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
